In [1]:
import numpy as np
a = np.array([4, 10, 12, 23, -2, -1, 0, 0, 0, -6, 3, -7])

In [4]:
a

array([ 4, 10, 12, 23, -2, -1,  0,  0,  0, -6,  3, -7])

1. How many negative numbers are there?

In [6]:
a[a < 0].shape

(4,)

2. How many positive numbers are there?

In [7]:
a[a > 0].shape

(5,)

3. How many even positive numbers are there?

In [10]:
(a[(a % 2 == 0) & (a > 0)]).shape

(3,)

4. If you were to add 3 to each data point, how many positive numbers would there be?

In [13]:
b = a + 3
b[b > 0].shape

(10,)

5. If you squared each number, what would the new mean and standard deviation be?

In [15]:
c = a ** 2
c.mean(), c.std()

(74.0, 144.0243035046516)

6. A common statistical operation on a dataset is centering. This means to adjust the data such that the mean of the data is 0. This is done by subtracting the mean from each data point. Center the data set. See this link for more on centering.

In [16]:
d = a.mean() - a
d

array([ -1.,  -7.,  -9., -20.,   5.,   4.,   3.,   3.,   3.,   9.,   0.,
        10.])

7. Calculate the z-score for each data point. Recall that the z-score is given by:

In [18]:
z_score = (a - a.mean() / a.std())
z_score

array([ 3.6278958,  9.6278958, 11.6278958, 22.6278958, -2.3721042,
       -1.3721042, -0.3721042, -0.3721042, -0.3721042, -6.3721042,
        2.6278958, -7.3721042])

In [45]:
import numpy as np
new_a = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
new_a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

Exercise 1 - Make a variable called sum_of_a to hold the sum of all the numbers in above list

In [46]:
sum_of_new_a = np.sum(new_a)
sum_of_new_a

55

Exercise 2 - Make a variable named min_of_a to hold the minimum of all the numbers in the above list

In [47]:
min_of_new_a = np.min(new_a)
min_of_new_a

1

Exercise 3 - Make a variable named max_of_a to hold the max number of all the numbers in the above list

In [27]:
max_of_new_a = np.max(new_a)
max_of_new_a

10

Exercise 4 - Make a variable named mean_of_a to hold the average of all the numbers in the above list

In [28]:
mean_of_new_a = np.mean(new_a)
mean_of_new_a

5.5

Exercise 5 - Make a variable named product_of_a to hold the product of multiplying all the numbers in the above list together

In [29]:
product_of_new_a = np.product(new_a)
product_of_new_a

3628800

Exercise 6 - Make a variable named squares_of_a. It should hold each number in a squared like [1, 4, 9, 16, 25...]

In [34]:
squares_of_new_a = np.square(new_a) 
squares_of_new_a

array([  1,   4,   9,  16,  25,  36,  49,  64,  81, 100])

Exercise 7 - Make a variable named odds_in_a. It should hold only the odd numbers

In [50]:
odds_in_new_a = new_a[new_a % 2 == 1]
odds_in_new_a

array([1, 3, 5, 7, 9])

Exercise 8 - Make a variable named evens_in_a. It should hold only the evens.

In [51]:
evens_in_new_a = new_a[new_a % 2 == 0]
evens_in_new_a

array([ 2,  4,  6,  8, 10])

Exercise 1 - refactor the following to use numpy. Use sum_of_b as the variable. **Hint, you'll first need to make sure that the "b" variable is a numpy array**

In [2]:
import numpy as np
b = np.array([[3, 4, 5], [6, 7, 8]])
b

array([[3, 4, 5],
       [6, 7, 8]])

In [3]:
sum_of_b = np.sum(b)
sum_of_b

33

Exercise 2 - refactor the following to use numpy. 
min_of_b = min(b[0]) if min(b[0]) <= min(b[1]) else min(b[1])  

In [4]:
min_of_b = np.min(b)
min_of_b

3

Exercise 3 - refactor the following maximum calculation to find the answer with numpy.
max_of_b = max(b[0]) if max(b[0]) >= max(b[1]) else max(b[1])

In [5]:
max_of_b = np.max(b)
max_of_b

8

Exercise 4 - refactor the following using numpy to find the mean of b
mean_of_b = (sum(b[0]) + sum(b[1])) / (len(b[0]) + len(b[1]))

In [6]:
mean_of_b = np.mean(b)
mean_of_b

5.5

Exercise 5 - refactor the following to use numpy for calculating the product of all numbers multiplied together.
product_of_b = 1
for row in b:
    for number in row:
        product_of_b *= number

In [7]:
product_of_b = np.product(b)
product_of_b

20160

Exercise 6 - refactor the following to use numpy to find the list of squares 
squares_of_b = []
for row in b:
    for number in row:
        squares_of_b.append(number**2)

In [8]:
squares_of_b = np.square(b)
squares_of_b

array([[ 9, 16, 25],
       [36, 49, 64]])

Exercise 7 - refactor using numpy to determine the odds_in_b
odds_in_b = []
for row in b:
    for number in row:
        if(number % 2 != 0):
            odds_in_b.append(number)

In [9]:
odds_in_b = b[b % 2 == 1]
odds_in_b

array([3, 5, 7])

Exercise 8 - refactor the following to use numpy to filter only the even numbers
evens_in_b = []
for row in b:
    for number in row:
        if(number % 2 == 0):
            evens_in_b.append(number)

In [10]:
evens_in_b = b[b % 2 == 0]
evens_in_b

array([4, 6, 8])

Exercise 9 - print out the shape of the array b.

In [11]:
shape_of_b = b.shape
shape_of_b

(2, 3)

Exercise 10 - transpose the array b.

In [12]:
transpose_b = np.transpose(b)
transpose_b

array([[3, 6],
       [4, 7],
       [5, 8]])

Exercise 11 - reshape the array b to be a single list of 6 numbers. (1 x 6)

In [13]:
reshape_array = b.reshape((6))
reshape_array

array([3, 4, 5, 6, 7, 8])

Exercise 12 - reshape the array b to be a list of 6 lists, each containing only 1 number (6 x 1)

In [18]:
reshape_array2 = b.reshape((6, 1))
reshape_array2

array([[3],
       [4],
       [5],
       [6],
       [7],
       [8]])

Exercise 1 - Find the min, max, sum, and product of c.

In [19]:
import numpy as np
c = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
c

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [21]:
min_of_c = np.min(c)
max_of_c = np.max(c)
product_of_c = np.product(c)
min_of_c, max_of_c, product_of_c

(1, 9, 362880)

Exercise 2 - Determine the standard deviation of c.

In [22]:
std_of_c = np.std(c)
std_of_c

2.581988897471611

Exercise 3 - Determine the variance of c.

In [25]:
variance_of_c = np.var(c)
variance_of_c

6.666666666666667

Exercise 4 - Print out the shape of the array c

In [26]:
shape_of_c = c.shape
shape_of_c

(3, 3)

Exercise 5 - Transpose c and print out transposed result.

In [27]:
transpose_c = np.transpose(c)
print(c)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


Exercise 6 - Get the dot product of the array c with c. 

In [29]:
dot_product_of_c = np.dot(c, c)
dot_product_of_c

array([[ 30,  36,  42],
       [ 66,  81,  96],
       [102, 126, 150]])

Exercise 7 - Write the code necessary to sum up the result of c times c transposed. Answer should be 261

In [31]:
result_of_c = transpose_c * c
sum_of_result_of_c = np.sum(result_of_c)
sum_of_result_of_c

261

Exercise 8 - Write the code necessary to determine the product of c times c transposed. Answer should be 131681894400.

In [32]:
sum2_of_result_of_c = np.product(result_of_c)
sum2_of_result_of_c

131681894400

Exercise 1 - Find the sine of all the numbers in d

In [34]:
import numpy as np
d = np.array([[90, 30, 45, 0, 120, 180],
    [45, -90, -30, 270, 90, 0],
    [60, 45, -45, 90, -45, 180]])
d

array([[ 90,  30,  45,   0, 120, 180],
       [ 45, -90, -30, 270,  90,   0],
       [ 60,  45, -45,  90, -45, 180]])

In [36]:
sine_of_d = np.sin(d)
sine_of_d

array([[ 0.89399666, -0.98803162,  0.85090352,  0.        ,  0.58061118,
        -0.80115264],
       [ 0.85090352, -0.89399666,  0.98803162, -0.17604595,  0.89399666,
         0.        ],
       [-0.30481062,  0.85090352, -0.85090352,  0.89399666, -0.85090352,
        -0.80115264]])

Exercise 2 - Find the cosine of all the numbers in d

In [37]:
cosine_of_d = np.cos(d)
cosine_of_d

array([[-0.44807362,  0.15425145,  0.52532199,  1.        ,  0.81418097,
        -0.59846007],
       [ 0.52532199, -0.44807362,  0.15425145,  0.98438195, -0.44807362,
         1.        ],
       [-0.95241298,  0.52532199,  0.52532199, -0.44807362,  0.52532199,
        -0.59846007]])

Exercise 3 - Find the tangent of all the numbers in d

In [38]:
tangent_of_d = np.tan(d)
tangent_of_d

array([[-1.99520041, -6.4053312 ,  1.61977519,  0.        ,  0.71312301,
         1.33869021],
       [ 1.61977519,  1.99520041,  6.4053312 , -0.17883906, -1.99520041,
         0.        ],
       [ 0.32004039,  1.61977519, -1.61977519, -1.99520041, -1.61977519,
         1.33869021]])

Exercise 4 - Find all the negative numbers in d

In [39]:
negative_num_d = d[d < 0]
negative_num_d

array([-90, -30, -45, -45])

Exercise 5 - Find all the positive numbers in d

In [40]:
pos_num_d = d[d > 0]
pos_num_d

array([ 90,  30,  45, 120, 180,  45, 270,  90,  60,  45,  90, 180])

Exercise 6 - Return an array of only the unique numbers in d.

In [41]:
unique_num_d = np.unique(d)
unique_num_d

array([-90, -45, -30,   0,  30,  45,  60,  90, 120, 180, 270])

Exercise 7 - Determine how many unique numbers there are in d.

In [42]:
unique_num_d.shape

(11,)

Exercise 8 - Print out the shape of d.

In [43]:
shape_of_d = d.shape
shape_of_d

(3, 6)

Exercise 9 - Transpose and then print out the shape of d.

In [44]:
transpose_d = np.transpose(d)
print(transpose_d.shape)

(6, 3)


Exercise 10 - Reshape d into an array of 9 x 2

In [45]:
reshape_array_d = d.reshape((9, 2))
reshape_array_d

array([[ 90,  30],
       [ 45,   0],
       [120, 180],
       [ 45, -90],
       [-30, 270],
       [ 90,   0],
       [ 60,  45],
       [-45,  90],
       [-45, 180]])